spring:
  redis:
    host: www.chenbk.club
    port: 6379
    database: 0
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password: lUjWdM91
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a168888
    url: jdbc:mysql://localhost:3306/test