spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a168888
    url: jdbc:mysql://localhost:3306/test
mybatis:
  mapper-locations: classpath*:com/chenbk/boot/mapping/*.xml
